/**
 * Passport scan factory — composition root для consent + audit + storage repos.
 *
 * Sprint C 2026-05-23: extracts `sql` import от routes так что depcruise
 * `no-routes-to-db` rule passes. Routes (consent-revoke / data-export /
 * vision) receive built repos через PassportScanFactory type instead of
 * raw sql.
 *
 * Pattern aligned с `booking.factory.ts`, `room.factory.ts`, etc. (15+
 * existing factory call sites в codebase).
 *
 * Self-review Sprint C fix 2026-05-23 (Y3 + H3 + H5):
 *   - ID generation HOISTED outside `sql.begin({idempotent:true})` — idempotent
 *     retry replays the callback; in-callback `newId()` would mint fresh IDs
 *     per retry → duplicate consent + audit rows on retryable error. Pre-gen
 *     ID outside tx + pass IN guarantees same ID across retries.
 *   - Revoke timestamp generated ONCE outside repo helpers, reused для both
 *     UPDATE clock и route response → no drift between operator API response
 *     and DSAR export.
 *   - cascadeRtbfRevoke returns explicit { revokedAt, alreadyRevoked } —
 *     truthful state (canonical fix vs old `{revoked:true}` always-lie).
 */

import { newId } from '@horeca/shared'
import type { sql as SQL } from '../../../db/index.ts'
import {
	createPassportOcrAuditRepo,
	type PassportOcrAuditRepo,
} from './audit/passport-ocr-audit.repo.ts'
import {
	createPhotoConsentLogRepo,
	type PhotoConsentLogRepo,
} from './consent/photo-consent-log.repo.ts'

export interface PassportScanFactory {
	readonly consentRepo: PhotoConsentLogRepo
	readonly auditRepo: PassportOcrAuditRepo
	/** Helper для transactional consent+audit write — used by vision.routes. */
	readonly recordConsentAndAuditAtomic: (input: AtomicWriteInput) => Promise<AtomicWriteResult>
	/** RTBF cascade — used by consent-revoke routes. nullify audit + revoke consent. */
	readonly cascadeRtbfRevoke: (input: RtbfRevokeInput) => Promise<RtbfRevokeResult>
}

interface AtomicWriteInput {
	/** Consent insert payload (id generated by factory outside tx). */
	readonly consent: Parameters<PhotoConsentLogRepo['insertWithId']>[1]
	/** Audit insert payload, photoConsentLogId stitched by factory. */
	readonly audit: Omit<Parameters<PassportOcrAuditRepo['insertWithId']>[1], 'photoConsentLogId'>
}

interface AtomicWriteResult {
	readonly success: boolean
	readonly consentId: string | null
}

interface RtbfRevokeInput {
	readonly tenantId: string
	readonly consentId: string
	readonly reason: string
}

export interface RtbfRevokeResult {
	/** Server-clock timestamp когда revoke applied (canonical для DSAR + response). */
	readonly revokedAt: Date
	/** False — мы just revoked; true — был уже revoked before our call. */
	readonly alreadyRevoked: boolean
	/** Server-stored reason verbatim (нашу call's reason ИЛИ pre-existing one). */
	readonly revokedReason: string
}

export function createPassportScanFactory(sql: typeof SQL): PassportScanFactory {
	const consentRepo = createPhotoConsentLogRepo(sql)
	const auditRepo = createPassportOcrAuditRepo(sql)

	const recordConsentAndAuditAtomic = async (
		input: AtomicWriteInput,
	): Promise<AtomicWriteResult> => {
		// Self-review Y3 fix: pre-generate IDs OUTSIDE sql.begin. `idempotent:true`
		// causes YDB driver to replay callback on retryable errors; in-callback
		// newId() would mint NEW UUIDs per attempt → duplicate rows committed
		// (best-effort dedup в repo via UPSERT не covers different IDs).
		const consentId = newId('consent')
		const auditId = newId('passportOcrAudit')
		try {
			await sql.begin({ idempotent: true }, async (tx) => {
				// `tx` has the tagged-template interface compatible с repos;
				// cast разрешает sub-type (no `begin`/`do` on tx — мы не nesting).
				const consentRepoTx = createPhotoConsentLogRepo(tx as unknown as typeof SQL)
				const auditRepoTx = createPassportOcrAuditRepo(tx as unknown as typeof SQL)
				await consentRepoTx.insertWithId(consentId, input.consent)
				await auditRepoTx.insertWithId(auditId, {
					...input.audit,
					photoConsentLogId: consentId,
				})
			})
			return { success: true, consentId }
		} catch {
			return { success: false, consentId: null }
		}
	}

	const cascadeRtbfRevoke = async (input: RtbfRevokeInput): Promise<RtbfRevokeResult> => {
		// Self-review H3 fix: single canonical timestamp shared across tx,
		// DSAR export, и operator API response — no clock-drift между repo
		// UPDATE и response body.
		const revokedAt = new Date()
		// Self-review H5: lookup ДО tx to determine alreadyRevoked truth-state.
		// Route's findById guard handles cross-tenant + missing — мы здесь
		// re-fetch к detect pre-revoked при concurrent calls (TOCTOU race window).
		const existing = await consentRepo.findById(input.tenantId, input.consentId)
		if (existing === null) {
			// Shouldn't reach — route filters. Defensive throw catches misuse.
			throw new Error(`cascadeRtbfRevoke: consent ${input.consentId} not found`)
		}
		if (existing.revokedAt !== null) {
			return {
				revokedAt: existing.revokedAt,
				alreadyRevoked: true,
				revokedReason: existing.revokedReason ?? '',
			}
		}
		await sql.begin({ idempotent: true }, async (tx) => {
			const auditRepoTx = createPassportOcrAuditRepo(tx as unknown as typeof SQL)
			const consentRepoTx = createPhotoConsentLogRepo(tx as unknown as typeof SQL)
			await auditRepoTx.nullifyEntitiesByConsentId(input.tenantId, input.consentId)
			await consentRepoTx.revokeAt(input.tenantId, input.consentId, input.reason, revokedAt)
		})
		return { revokedAt, alreadyRevoked: false, revokedReason: input.reason }
	}

	return {
		consentRepo,
		auditRepo,
		recordConsentAndAuditAtomic,
		cascadeRtbfRevoke,
	}
}
