/**
 * postMessage protocol shared between embed widget iframe (Lit element on
 * parent side) and SPA (child side rendered inside iframe).
 *
 * **No zod runtime.** This module is types + const literals ONLY. Each
 * consumer ships its own slim manual validator (`validateMessage`) so that
 * embed widget bundles стай under their kB budgets — pulling zod into a
 * 15 KB facade ceiling would blow it. Drift defense: identical shape
 * required в both validators; integration tests verify roundtrip.
 *
 * M9.widget.6 / А4.4 D32 nonce-binding canon:
 *   - Per-session `nonce = crypto.randomUUID()` generated by parent BEFORE
 *     iframe creation; passed via URL fragment `#nonce=...`.
 *   - Child echoes nonce in its first `'ready'` ping.
 *   - Parent rejects ports/messages with mismatched nonce — defends the
 *     init-message race CVE-2024-49038 class (Microsoft Copilot Studio
 *     CVSS 9.3).
 *   - Subsequent messages carry monotonic `seq` counter (replay defense).
 *
 * Namespace `ns: 'sochi-widget'` keeps us out of WorkOS / Stripe / analytics
 * collisions when multiple postMessage producers share the parent window.
 */

export const WIDGET_PROTOCOL_NS = 'sochi-widget'
export const WIDGET_PROTOCOL_VERSION = 1
export const WIDGET_RESIZE_HEIGHT_MAX = 4096

export type WidgetMessageType =
	| 'ready'
	| 'init'
	| 'resize'
	| 'navigate'
	| 'booking-complete'
	| 'error'

interface WidgetEnvelopeBase<TType extends WidgetMessageType> {
	readonly ns: typeof WIDGET_PROTOCOL_NS
	readonly v: typeof WIDGET_PROTOCOL_VERSION
	readonly type: TType
	readonly nonce: string
	readonly seq: number
}

/** Child posts to parent on `connectedCallback` start (D35 child-ready handshake). */
export type WidgetReadyMessage = WidgetEnvelopeBase<'ready'>

/**
 * Parent posts to child after `'ready'` received. Carries `MessagePort`
 * transferred via `postMessage(msg, origin, [port])`. Subsequent traffic
 * flows over the port (eavesdrop-resistant per MDN MessageChannel canon).
 */
export interface WidgetInitMessage extends WidgetEnvelopeBase<'init'> {
	readonly parentOrigin: string
}

/**
 * Child posts to parent с new content height when ResizeObserver fires.
 * Hard cap WIDGET_RESIZE_HEIGHT_MAX (4096px) defends pathological
 * infinite-loop layout patterns (D33).
 */
export interface WidgetResizeMessage extends WidgetEnvelopeBase<'resize'> {
	readonly height: number
}

/**
 * Child requests parent-level navigation (magic-link `target="_top"`
 * fallback when sandbox forbids top-navigation per D30 / CVE-2026-5903).
 * Parent validates URL host whitelist before applying.
 */
export interface WidgetNavigateMessage extends WidgetEnvelopeBase<'navigate'> {
	readonly href: string
}

/**
 * Child signals successful booking; parent emits `CustomEvent` so tenant
 * page can fire its own analytics goal.
 */
export interface WidgetBookingCompleteMessage extends WidgetEnvelopeBase<'booking-complete'> {
	readonly bookingRef: string
}

/**
 * Generic error signal. Telemetry only — parent never acts on attacker-
 * controllable error payload без out-of-band verification.
 */
export interface WidgetErrorMessage extends WidgetEnvelopeBase<'error'> {
	readonly code: string
	readonly message: string
}

export type WidgetMessage =
	| WidgetReadyMessage
	| WidgetInitMessage
	| WidgetResizeMessage
	| WidgetNavigateMessage
	| WidgetBookingCompleteMessage
	| WidgetErrorMessage

/**
 * Slim manual validator — keeps zod runtime out of consumer bundles. Both
 * widget-embed iframe-fallback element AND apps/frontend SPA bridge
 * import this directly. Tested by both ends so drift surfaces immediately.
 *
 * Returns the typed message on valid input, `null` otherwise — caller
 * silently drops invalid messages (anti-fuzzing telemetry stays out of
 * production logs).
 */
export function validateWidgetMessage(input: unknown): WidgetMessage | null {
	if (typeof input !== 'object' || input === null) return null
	const o = input as Record<string, unknown>
	if (o.ns !== WIDGET_PROTOCOL_NS) return null
	if (o.v !== WIDGET_PROTOCOL_VERSION) return null
	if (typeof o.nonce !== 'string' || o.nonce.length === 0 || o.nonce.length > 64) return null
	if (typeof o.seq !== 'number' || !Number.isInteger(o.seq) || o.seq < 0) return null
	switch (o.type) {
		case 'ready':
			return input as WidgetReadyMessage
		case 'init':
			if (typeof o.parentOrigin !== 'string' || o.parentOrigin.length === 0) return null
			return input as WidgetInitMessage
		case 'resize':
			if (
				typeof o.height !== 'number' ||
				!Number.isInteger(o.height) ||
				o.height < 0 ||
				o.height > WIDGET_RESIZE_HEIGHT_MAX
			) {
				return null
			}
			return input as WidgetResizeMessage
		case 'navigate':
			if (typeof o.href !== 'string' || !o.href.startsWith('https://')) return null
			return input as WidgetNavigateMessage
		case 'booking-complete':
			if (typeof o.bookingRef !== 'string' || o.bookingRef.length === 0) return null
			return input as WidgetBookingCompleteMessage
		case 'error':
			if (typeof o.code !== 'string' || typeof o.message !== 'string') return null
			return input as WidgetErrorMessage
		default:
			return null
	}
}
