/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as WidgetTenantSlugRouteImport } from './routes/widget.$tenantSlug'
import { Route as DemoShowcaseRouteImport } from './routes/demo.showcase'
import { Route as BookingJwtRouteImport } from './routes/booking.$jwt'
import { Route as AppOSelectRouteImport } from './routes/_app.o-select'
import { Route as WidgetTenantSlugPropertyIdRouteImport } from './routes/widget.$tenantSlug_.$propertyId'
import { Route as BookingGuestPortalBookingIdRouteImport } from './routes/booking.guest-portal.$bookingId'
import { Route as AppOOrgSlugRouteImport } from './routes/_app.o.$orgSlug'
import { Route as DemoOtaYandexIndexRouteImport } from './routes/demo.ota.yandex.index'
import { Route as DemoOtaOstrovokIndexRouteImport } from './routes/demo.ota.ostrovok.index'
import { Route as AppOOrgSlugIndexRouteImport } from './routes/_app.o.$orgSlug.index'
import { Route as WidgetTenantSlugPropertyIdGuestAndPayRouteImport } from './routes/widget.$tenantSlug_.$propertyId_.guest-and-pay'
import { Route as WidgetTenantSlugPropertyIdExtrasRouteImport } from './routes/widget.$tenantSlug_.$propertyId_.extras'
import { Route as AppOOrgSlugSetupRouteImport } from './routes/_app.o.$orgSlug.setup'
import { Route as AppOOrgSlugReviewsRouteImport } from './routes/_app.o.$orgSlug.reviews'
import { Route as AppOOrgSlugReceivablesRouteImport } from './routes/_app.o.$orgSlug.receivables'
import { Route as AppOOrgSlugGridRouteImport } from './routes/_app.o.$orgSlug.grid'
import { Route as AppOOrgSlugDemoRouteImport } from './routes/_app.o.$orgSlug.demo'
import { Route as DemoOtaYandexSuccessOrderIdRouteImport } from './routes/demo.ota.yandex.success.$orderId'
import { Route as DemoOtaYandexPropertyIdRouteImport } from './routes/demo.ota.yandex.property.$id'
import { Route as DemoOtaYandexBookingBookingTokenRouteImport } from './routes/demo.ota.yandex.booking.$bookingToken'
import { Route as DemoOtaOstrovokSuccessOrderIdRouteImport } from './routes/demo.ota.ostrovok.success.$orderId'
import { Route as DemoOtaOstrovokPropertyIdRouteImport } from './routes/demo.ota.ostrovok.property.$id'
import { Route as DemoOtaOstrovokBookingPartnerOrderIdRouteImport } from './routes/demo.ota.ostrovok.booking.$partnerOrderId'
import { Route as AppOOrgSlugAdminTaxRouteImport } from './routes/_app.o.$orgSlug.admin.tax'
import { Route as AppOOrgSlugAdminNotificationsRouteImport } from './routes/_app.o.$orgSlug.admin.notifications'
import { Route as AppOOrgSlugAdminMigrationRegistrationsRouteImport } from './routes/_app.o.$orgSlug.admin.migration-registrations'
import { Route as AppOOrgSlugAdminChannelsRouteImport } from './routes/_app.o.$orgSlug.admin.channels'
import { Route as AppOOrgSlugAccountSecurityRouteImport } from './routes/_app.o.$orgSlug.account.security'
import { Route as AppOOrgSlugPropertiesPropertyIdInventoryRouteImport } from './routes/_app.o.$orgSlug.properties.$propertyId.inventory'
import { Route as AppOOrgSlugPropertiesPropertyIdContentRouteImport } from './routes/_app.o.$orgSlug.properties.$propertyId.content'
import { Route as AppOOrgSlugPropertiesPropertyIdInventoryRoomsRouteImport } from './routes/_app.o.$orgSlug.properties.$propertyId.inventory.rooms'
import { Route as AppOOrgSlugPropertiesPropertyIdInventoryRatePlansRouteImport } from './routes/_app.o.$orgSlug.properties.$propertyId.inventory.rate-plans'
import { Route as AppOOrgSlugPropertiesPropertyIdInventoryPricesRouteImport } from './routes/_app.o.$orgSlug.properties.$propertyId.inventory.prices'
import { Route as AppOOrgSlugBookingsBookingIdFoliosFolioIdRouteImport } from './routes/_app.o.$orgSlug.bookings.$bookingId.folios.$folioId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const WidgetTenantSlugRoute = WidgetTenantSlugRouteImport.update({
  id: '/widget/$tenantSlug',
  path: '/widget/$tenantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoShowcaseRoute = DemoShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => DemoRoute,
} as any)
const BookingJwtRoute = BookingJwtRouteImport.update({
  id: '/booking/$jwt',
  path: '/booking/$jwt',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOSelectRoute = AppOSelectRouteImport.update({
  id: '/o-select',
  path: '/o-select',
  getParentRoute: () => AppRoute,
} as any)
const WidgetTenantSlugPropertyIdRoute =
  WidgetTenantSlugPropertyIdRouteImport.update({
    id: '/widget/$tenantSlug_/$propertyId',
    path: '/widget/$tenantSlug/$propertyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookingGuestPortalBookingIdRoute =
  BookingGuestPortalBookingIdRouteImport.update({
    id: '/booking/guest-portal/$bookingId',
    path: '/booking/guest-portal/$bookingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOOrgSlugRoute = AppOOrgSlugRouteImport.update({
  id: '/o/$orgSlug',
  path: '/o/$orgSlug',
  getParentRoute: () => AppRoute,
} as any)
const DemoOtaYandexIndexRoute = DemoOtaYandexIndexRouteImport.update({
  id: '/ota/yandex/',
  path: '/ota/yandex/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoOtaOstrovokIndexRoute = DemoOtaOstrovokIndexRouteImport.update({
  id: '/ota/ostrovok/',
  path: '/ota/ostrovok/',
  getParentRoute: () => DemoRoute,
} as any)
const AppOOrgSlugIndexRoute = AppOOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOOrgSlugRoute,
} as any)
const WidgetTenantSlugPropertyIdGuestAndPayRoute =
  WidgetTenantSlugPropertyIdGuestAndPayRouteImport.update({
    id: '/widget/$tenantSlug_/$propertyId_/guest-and-pay',
    path: '/widget/$tenantSlug/$propertyId/guest-and-pay',
    getParentRoute: () => rootRouteImport,
  } as any)
const WidgetTenantSlugPropertyIdExtrasRoute =
  WidgetTenantSlugPropertyIdExtrasRouteImport.update({
    id: '/widget/$tenantSlug_/$propertyId_/extras',
    path: '/widget/$tenantSlug/$propertyId/extras',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOOrgSlugSetupRoute = AppOOrgSlugSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppOOrgSlugRoute,
} as any)
const AppOOrgSlugReviewsRoute = AppOOrgSlugReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppOOrgSlugRoute,
} as any)
const AppOOrgSlugReceivablesRoute = AppOOrgSlugReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => AppOOrgSlugRoute,
} as any)
const AppOOrgSlugGridRoute = AppOOrgSlugGridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => AppOOrgSlugRoute,
} as any)
const AppOOrgSlugDemoRoute = AppOOrgSlugDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AppOOrgSlugRoute,
} as any)
const DemoOtaYandexSuccessOrderIdRoute =
  DemoOtaYandexSuccessOrderIdRouteImport.update({
    id: '/ota/yandex/success/$orderId',
    path: '/ota/yandex/success/$orderId',
    getParentRoute: () => DemoRoute,
  } as any)
const DemoOtaYandexPropertyIdRoute = DemoOtaYandexPropertyIdRouteImport.update({
  id: '/ota/yandex/property/$id',
  path: '/ota/yandex/property/$id',
  getParentRoute: () => DemoRoute,
} as any)
const DemoOtaYandexBookingBookingTokenRoute =
  DemoOtaYandexBookingBookingTokenRouteImport.update({
    id: '/ota/yandex/booking/$bookingToken',
    path: '/ota/yandex/booking/$bookingToken',
    getParentRoute: () => DemoRoute,
  } as any)
const DemoOtaOstrovokSuccessOrderIdRoute =
  DemoOtaOstrovokSuccessOrderIdRouteImport.update({
    id: '/ota/ostrovok/success/$orderId',
    path: '/ota/ostrovok/success/$orderId',
    getParentRoute: () => DemoRoute,
  } as any)
const DemoOtaOstrovokPropertyIdRoute =
  DemoOtaOstrovokPropertyIdRouteImport.update({
    id: '/ota/ostrovok/property/$id',
    path: '/ota/ostrovok/property/$id',
    getParentRoute: () => DemoRoute,
  } as any)
const DemoOtaOstrovokBookingPartnerOrderIdRoute =
  DemoOtaOstrovokBookingPartnerOrderIdRouteImport.update({
    id: '/ota/ostrovok/booking/$partnerOrderId',
    path: '/ota/ostrovok/booking/$partnerOrderId',
    getParentRoute: () => DemoRoute,
  } as any)
const AppOOrgSlugAdminTaxRoute = AppOOrgSlugAdminTaxRouteImport.update({
  id: '/admin/tax',
  path: '/admin/tax',
  getParentRoute: () => AppOOrgSlugRoute,
} as any)
const AppOOrgSlugAdminNotificationsRoute =
  AppOOrgSlugAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AppOOrgSlugRoute,
  } as any)
const AppOOrgSlugAdminMigrationRegistrationsRoute =
  AppOOrgSlugAdminMigrationRegistrationsRouteImport.update({
    id: '/admin/migration-registrations',
    path: '/admin/migration-registrations',
    getParentRoute: () => AppOOrgSlugRoute,
  } as any)
const AppOOrgSlugAdminChannelsRoute =
  AppOOrgSlugAdminChannelsRouteImport.update({
    id: '/admin/channels',
    path: '/admin/channels',
    getParentRoute: () => AppOOrgSlugRoute,
  } as any)
const AppOOrgSlugAccountSecurityRoute =
  AppOOrgSlugAccountSecurityRouteImport.update({
    id: '/account/security',
    path: '/account/security',
    getParentRoute: () => AppOOrgSlugRoute,
  } as any)
const AppOOrgSlugPropertiesPropertyIdInventoryRoute =
  AppOOrgSlugPropertiesPropertyIdInventoryRouteImport.update({
    id: '/properties/$propertyId/inventory',
    path: '/properties/$propertyId/inventory',
    getParentRoute: () => AppOOrgSlugRoute,
  } as any)
const AppOOrgSlugPropertiesPropertyIdContentRoute =
  AppOOrgSlugPropertiesPropertyIdContentRouteImport.update({
    id: '/properties/$propertyId/content',
    path: '/properties/$propertyId/content',
    getParentRoute: () => AppOOrgSlugRoute,
  } as any)
const AppOOrgSlugPropertiesPropertyIdInventoryRoomsRoute =
  AppOOrgSlugPropertiesPropertyIdInventoryRoomsRouteImport.update({
    id: '/rooms',
    path: '/rooms',
    getParentRoute: () => AppOOrgSlugPropertiesPropertyIdInventoryRoute,
  } as any)
const AppOOrgSlugPropertiesPropertyIdInventoryRatePlansRoute =
  AppOOrgSlugPropertiesPropertyIdInventoryRatePlansRouteImport.update({
    id: '/rate-plans',
    path: '/rate-plans',
    getParentRoute: () => AppOOrgSlugPropertiesPropertyIdInventoryRoute,
  } as any)
const AppOOrgSlugPropertiesPropertyIdInventoryPricesRoute =
  AppOOrgSlugPropertiesPropertyIdInventoryPricesRouteImport.update({
    id: '/prices',
    path: '/prices',
    getParentRoute: () => AppOOrgSlugPropertiesPropertyIdInventoryRoute,
  } as any)
const AppOOrgSlugBookingsBookingIdFoliosFolioIdRoute =
  AppOOrgSlugBookingsBookingIdFoliosFolioIdRouteImport.update({
    id: '/bookings/$bookingId/folios/$folioId',
    path: '/bookings/$bookingId/folios/$folioId',
    getParentRoute: () => AppOOrgSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/o-select': typeof AppOSelectRoute
  '/booking/$jwt': typeof BookingJwtRoute
  '/demo/showcase': typeof DemoShowcaseRoute
  '/widget/$tenantSlug': typeof WidgetTenantSlugRoute
  '/demo/': typeof DemoIndexRoute
  '/o/$orgSlug': typeof AppOOrgSlugRouteWithChildren
  '/booking/guest-portal/$bookingId': typeof BookingGuestPortalBookingIdRoute
  '/widget/$tenantSlug/$propertyId': typeof WidgetTenantSlugPropertyIdRoute
  '/o/$orgSlug/demo': typeof AppOOrgSlugDemoRoute
  '/o/$orgSlug/grid': typeof AppOOrgSlugGridRoute
  '/o/$orgSlug/receivables': typeof AppOOrgSlugReceivablesRoute
  '/o/$orgSlug/reviews': typeof AppOOrgSlugReviewsRoute
  '/o/$orgSlug/setup': typeof AppOOrgSlugSetupRoute
  '/widget/$tenantSlug/$propertyId/extras': typeof WidgetTenantSlugPropertyIdExtrasRoute
  '/widget/$tenantSlug/$propertyId/guest-and-pay': typeof WidgetTenantSlugPropertyIdGuestAndPayRoute
  '/o/$orgSlug/': typeof AppOOrgSlugIndexRoute
  '/demo/ota/ostrovok/': typeof DemoOtaOstrovokIndexRoute
  '/demo/ota/yandex/': typeof DemoOtaYandexIndexRoute
  '/o/$orgSlug/account/security': typeof AppOOrgSlugAccountSecurityRoute
  '/o/$orgSlug/admin/channels': typeof AppOOrgSlugAdminChannelsRoute
  '/o/$orgSlug/admin/migration-registrations': typeof AppOOrgSlugAdminMigrationRegistrationsRoute
  '/o/$orgSlug/admin/notifications': typeof AppOOrgSlugAdminNotificationsRoute
  '/o/$orgSlug/admin/tax': typeof AppOOrgSlugAdminTaxRoute
  '/demo/ota/ostrovok/booking/$partnerOrderId': typeof DemoOtaOstrovokBookingPartnerOrderIdRoute
  '/demo/ota/ostrovok/property/$id': typeof DemoOtaOstrovokPropertyIdRoute
  '/demo/ota/ostrovok/success/$orderId': typeof DemoOtaOstrovokSuccessOrderIdRoute
  '/demo/ota/yandex/booking/$bookingToken': typeof DemoOtaYandexBookingBookingTokenRoute
  '/demo/ota/yandex/property/$id': typeof DemoOtaYandexPropertyIdRoute
  '/demo/ota/yandex/success/$orderId': typeof DemoOtaYandexSuccessOrderIdRoute
  '/o/$orgSlug/properties/$propertyId/content': typeof AppOOrgSlugPropertiesPropertyIdContentRoute
  '/o/$orgSlug/properties/$propertyId/inventory': typeof AppOOrgSlugPropertiesPropertyIdInventoryRouteWithChildren
  '/o/$orgSlug/bookings/$bookingId/folios/$folioId': typeof AppOOrgSlugBookingsBookingIdFoliosFolioIdRoute
  '/o/$orgSlug/properties/$propertyId/inventory/prices': typeof AppOOrgSlugPropertiesPropertyIdInventoryPricesRoute
  '/o/$orgSlug/properties/$propertyId/inventory/rate-plans': typeof AppOOrgSlugPropertiesPropertyIdInventoryRatePlansRoute
  '/o/$orgSlug/properties/$propertyId/inventory/rooms': typeof AppOOrgSlugPropertiesPropertyIdInventoryRoomsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/o-select': typeof AppOSelectRoute
  '/booking/$jwt': typeof BookingJwtRoute
  '/demo/showcase': typeof DemoShowcaseRoute
  '/widget/$tenantSlug': typeof WidgetTenantSlugRoute
  '/demo': typeof DemoIndexRoute
  '/booking/guest-portal/$bookingId': typeof BookingGuestPortalBookingIdRoute
  '/widget/$tenantSlug/$propertyId': typeof WidgetTenantSlugPropertyIdRoute
  '/o/$orgSlug/demo': typeof AppOOrgSlugDemoRoute
  '/o/$orgSlug/grid': typeof AppOOrgSlugGridRoute
  '/o/$orgSlug/receivables': typeof AppOOrgSlugReceivablesRoute
  '/o/$orgSlug/reviews': typeof AppOOrgSlugReviewsRoute
  '/o/$orgSlug/setup': typeof AppOOrgSlugSetupRoute
  '/widget/$tenantSlug/$propertyId/extras': typeof WidgetTenantSlugPropertyIdExtrasRoute
  '/widget/$tenantSlug/$propertyId/guest-and-pay': typeof WidgetTenantSlugPropertyIdGuestAndPayRoute
  '/o/$orgSlug': typeof AppOOrgSlugIndexRoute
  '/demo/ota/ostrovok': typeof DemoOtaOstrovokIndexRoute
  '/demo/ota/yandex': typeof DemoOtaYandexIndexRoute
  '/o/$orgSlug/account/security': typeof AppOOrgSlugAccountSecurityRoute
  '/o/$orgSlug/admin/channels': typeof AppOOrgSlugAdminChannelsRoute
  '/o/$orgSlug/admin/migration-registrations': typeof AppOOrgSlugAdminMigrationRegistrationsRoute
  '/o/$orgSlug/admin/notifications': typeof AppOOrgSlugAdminNotificationsRoute
  '/o/$orgSlug/admin/tax': typeof AppOOrgSlugAdminTaxRoute
  '/demo/ota/ostrovok/booking/$partnerOrderId': typeof DemoOtaOstrovokBookingPartnerOrderIdRoute
  '/demo/ota/ostrovok/property/$id': typeof DemoOtaOstrovokPropertyIdRoute
  '/demo/ota/ostrovok/success/$orderId': typeof DemoOtaOstrovokSuccessOrderIdRoute
  '/demo/ota/yandex/booking/$bookingToken': typeof DemoOtaYandexBookingBookingTokenRoute
  '/demo/ota/yandex/property/$id': typeof DemoOtaYandexPropertyIdRoute
  '/demo/ota/yandex/success/$orderId': typeof DemoOtaYandexSuccessOrderIdRoute
  '/o/$orgSlug/properties/$propertyId/content': typeof AppOOrgSlugPropertiesPropertyIdContentRoute
  '/o/$orgSlug/properties/$propertyId/inventory': typeof AppOOrgSlugPropertiesPropertyIdInventoryRouteWithChildren
  '/o/$orgSlug/bookings/$bookingId/folios/$folioId': typeof AppOOrgSlugBookingsBookingIdFoliosFolioIdRoute
  '/o/$orgSlug/properties/$propertyId/inventory/prices': typeof AppOOrgSlugPropertiesPropertyIdInventoryPricesRoute
  '/o/$orgSlug/properties/$propertyId/inventory/rate-plans': typeof AppOOrgSlugPropertiesPropertyIdInventoryRatePlansRoute
  '/o/$orgSlug/properties/$propertyId/inventory/rooms': typeof AppOOrgSlugPropertiesPropertyIdInventoryRoomsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/_app/o-select': typeof AppOSelectRoute
  '/booking/$jwt': typeof BookingJwtRoute
  '/demo/showcase': typeof DemoShowcaseRoute
  '/widget/$tenantSlug': typeof WidgetTenantSlugRoute
  '/demo/': typeof DemoIndexRoute
  '/_app/o/$orgSlug': typeof AppOOrgSlugRouteWithChildren
  '/booking/guest-portal/$bookingId': typeof BookingGuestPortalBookingIdRoute
  '/widget/$tenantSlug_/$propertyId': typeof WidgetTenantSlugPropertyIdRoute
  '/_app/o/$orgSlug/demo': typeof AppOOrgSlugDemoRoute
  '/_app/o/$orgSlug/grid': typeof AppOOrgSlugGridRoute
  '/_app/o/$orgSlug/receivables': typeof AppOOrgSlugReceivablesRoute
  '/_app/o/$orgSlug/reviews': typeof AppOOrgSlugReviewsRoute
  '/_app/o/$orgSlug/setup': typeof AppOOrgSlugSetupRoute
  '/widget/$tenantSlug_/$propertyId_/extras': typeof WidgetTenantSlugPropertyIdExtrasRoute
  '/widget/$tenantSlug_/$propertyId_/guest-and-pay': typeof WidgetTenantSlugPropertyIdGuestAndPayRoute
  '/_app/o/$orgSlug/': typeof AppOOrgSlugIndexRoute
  '/demo/ota/ostrovok/': typeof DemoOtaOstrovokIndexRoute
  '/demo/ota/yandex/': typeof DemoOtaYandexIndexRoute
  '/_app/o/$orgSlug/account/security': typeof AppOOrgSlugAccountSecurityRoute
  '/_app/o/$orgSlug/admin/channels': typeof AppOOrgSlugAdminChannelsRoute
  '/_app/o/$orgSlug/admin/migration-registrations': typeof AppOOrgSlugAdminMigrationRegistrationsRoute
  '/_app/o/$orgSlug/admin/notifications': typeof AppOOrgSlugAdminNotificationsRoute
  '/_app/o/$orgSlug/admin/tax': typeof AppOOrgSlugAdminTaxRoute
  '/demo/ota/ostrovok/booking/$partnerOrderId': typeof DemoOtaOstrovokBookingPartnerOrderIdRoute
  '/demo/ota/ostrovok/property/$id': typeof DemoOtaOstrovokPropertyIdRoute
  '/demo/ota/ostrovok/success/$orderId': typeof DemoOtaOstrovokSuccessOrderIdRoute
  '/demo/ota/yandex/booking/$bookingToken': typeof DemoOtaYandexBookingBookingTokenRoute
  '/demo/ota/yandex/property/$id': typeof DemoOtaYandexPropertyIdRoute
  '/demo/ota/yandex/success/$orderId': typeof DemoOtaYandexSuccessOrderIdRoute
  '/_app/o/$orgSlug/properties/$propertyId/content': typeof AppOOrgSlugPropertiesPropertyIdContentRoute
  '/_app/o/$orgSlug/properties/$propertyId/inventory': typeof AppOOrgSlugPropertiesPropertyIdInventoryRouteWithChildren
  '/_app/o/$orgSlug/bookings/$bookingId/folios/$folioId': typeof AppOOrgSlugBookingsBookingIdFoliosFolioIdRoute
  '/_app/o/$orgSlug/properties/$propertyId/inventory/prices': typeof AppOOrgSlugPropertiesPropertyIdInventoryPricesRoute
  '/_app/o/$orgSlug/properties/$propertyId/inventory/rate-plans': typeof AppOOrgSlugPropertiesPropertyIdInventoryRatePlansRoute
  '/_app/o/$orgSlug/properties/$propertyId/inventory/rooms': typeof AppOOrgSlugPropertiesPropertyIdInventoryRoomsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/welcome'
    | '/o-select'
    | '/booking/$jwt'
    | '/demo/showcase'
    | '/widget/$tenantSlug'
    | '/demo/'
    | '/o/$orgSlug'
    | '/booking/guest-portal/$bookingId'
    | '/widget/$tenantSlug/$propertyId'
    | '/o/$orgSlug/demo'
    | '/o/$orgSlug/grid'
    | '/o/$orgSlug/receivables'
    | '/o/$orgSlug/reviews'
    | '/o/$orgSlug/setup'
    | '/widget/$tenantSlug/$propertyId/extras'
    | '/widget/$tenantSlug/$propertyId/guest-and-pay'
    | '/o/$orgSlug/'
    | '/demo/ota/ostrovok/'
    | '/demo/ota/yandex/'
    | '/o/$orgSlug/account/security'
    | '/o/$orgSlug/admin/channels'
    | '/o/$orgSlug/admin/migration-registrations'
    | '/o/$orgSlug/admin/notifications'
    | '/o/$orgSlug/admin/tax'
    | '/demo/ota/ostrovok/booking/$partnerOrderId'
    | '/demo/ota/ostrovok/property/$id'
    | '/demo/ota/ostrovok/success/$orderId'
    | '/demo/ota/yandex/booking/$bookingToken'
    | '/demo/ota/yandex/property/$id'
    | '/demo/ota/yandex/success/$orderId'
    | '/o/$orgSlug/properties/$propertyId/content'
    | '/o/$orgSlug/properties/$propertyId/inventory'
    | '/o/$orgSlug/bookings/$bookingId/folios/$folioId'
    | '/o/$orgSlug/properties/$propertyId/inventory/prices'
    | '/o/$orgSlug/properties/$propertyId/inventory/rate-plans'
    | '/o/$orgSlug/properties/$propertyId/inventory/rooms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/welcome'
    | '/o-select'
    | '/booking/$jwt'
    | '/demo/showcase'
    | '/widget/$tenantSlug'
    | '/demo'
    | '/booking/guest-portal/$bookingId'
    | '/widget/$tenantSlug/$propertyId'
    | '/o/$orgSlug/demo'
    | '/o/$orgSlug/grid'
    | '/o/$orgSlug/receivables'
    | '/o/$orgSlug/reviews'
    | '/o/$orgSlug/setup'
    | '/widget/$tenantSlug/$propertyId/extras'
    | '/widget/$tenantSlug/$propertyId/guest-and-pay'
    | '/o/$orgSlug'
    | '/demo/ota/ostrovok'
    | '/demo/ota/yandex'
    | '/o/$orgSlug/account/security'
    | '/o/$orgSlug/admin/channels'
    | '/o/$orgSlug/admin/migration-registrations'
    | '/o/$orgSlug/admin/notifications'
    | '/o/$orgSlug/admin/tax'
    | '/demo/ota/ostrovok/booking/$partnerOrderId'
    | '/demo/ota/ostrovok/property/$id'
    | '/demo/ota/ostrovok/success/$orderId'
    | '/demo/ota/yandex/booking/$bookingToken'
    | '/demo/ota/yandex/property/$id'
    | '/demo/ota/yandex/success/$orderId'
    | '/o/$orgSlug/properties/$propertyId/content'
    | '/o/$orgSlug/properties/$propertyId/inventory'
    | '/o/$orgSlug/bookings/$bookingId/folios/$folioId'
    | '/o/$orgSlug/properties/$propertyId/inventory/prices'
    | '/o/$orgSlug/properties/$propertyId/inventory/rate-plans'
    | '/o/$orgSlug/properties/$propertyId/inventory/rooms'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/demo'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/welcome'
    | '/_app/o-select'
    | '/booking/$jwt'
    | '/demo/showcase'
    | '/widget/$tenantSlug'
    | '/demo/'
    | '/_app/o/$orgSlug'
    | '/booking/guest-portal/$bookingId'
    | '/widget/$tenantSlug_/$propertyId'
    | '/_app/o/$orgSlug/demo'
    | '/_app/o/$orgSlug/grid'
    | '/_app/o/$orgSlug/receivables'
    | '/_app/o/$orgSlug/reviews'
    | '/_app/o/$orgSlug/setup'
    | '/widget/$tenantSlug_/$propertyId_/extras'
    | '/widget/$tenantSlug_/$propertyId_/guest-and-pay'
    | '/_app/o/$orgSlug/'
    | '/demo/ota/ostrovok/'
    | '/demo/ota/yandex/'
    | '/_app/o/$orgSlug/account/security'
    | '/_app/o/$orgSlug/admin/channels'
    | '/_app/o/$orgSlug/admin/migration-registrations'
    | '/_app/o/$orgSlug/admin/notifications'
    | '/_app/o/$orgSlug/admin/tax'
    | '/demo/ota/ostrovok/booking/$partnerOrderId'
    | '/demo/ota/ostrovok/property/$id'
    | '/demo/ota/ostrovok/success/$orderId'
    | '/demo/ota/yandex/booking/$bookingToken'
    | '/demo/ota/yandex/property/$id'
    | '/demo/ota/yandex/success/$orderId'
    | '/_app/o/$orgSlug/properties/$propertyId/content'
    | '/_app/o/$orgSlug/properties/$propertyId/inventory'
    | '/_app/o/$orgSlug/bookings/$bookingId/folios/$folioId'
    | '/_app/o/$orgSlug/properties/$propertyId/inventory/prices'
    | '/_app/o/$orgSlug/properties/$propertyId/inventory/rate-plans'
    | '/_app/o/$orgSlug/properties/$propertyId/inventory/rooms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  WelcomeRoute: typeof WelcomeRoute
  BookingJwtRoute: typeof BookingJwtRoute
  WidgetTenantSlugRoute: typeof WidgetTenantSlugRoute
  BookingGuestPortalBookingIdRoute: typeof BookingGuestPortalBookingIdRoute
  WidgetTenantSlugPropertyIdRoute: typeof WidgetTenantSlugPropertyIdRoute
  WidgetTenantSlugPropertyIdExtrasRoute: typeof WidgetTenantSlugPropertyIdExtrasRoute
  WidgetTenantSlugPropertyIdGuestAndPayRoute: typeof WidgetTenantSlugPropertyIdGuestAndPayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/widget/$tenantSlug': {
      id: '/widget/$tenantSlug'
      path: '/widget/$tenantSlug'
      fullPath: '/widget/$tenantSlug'
      preLoaderRoute: typeof WidgetTenantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/showcase': {
      id: '/demo/showcase'
      path: '/showcase'
      fullPath: '/demo/showcase'
      preLoaderRoute: typeof DemoShowcaseRouteImport
      parentRoute: typeof DemoRoute
    }
    '/booking/$jwt': {
      id: '/booking/$jwt'
      path: '/booking/$jwt'
      fullPath: '/booking/$jwt'
      preLoaderRoute: typeof BookingJwtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/o-select': {
      id: '/_app/o-select'
      path: '/o-select'
      fullPath: '/o-select'
      preLoaderRoute: typeof AppOSelectRouteImport
      parentRoute: typeof AppRoute
    }
    '/widget/$tenantSlug_/$propertyId': {
      id: '/widget/$tenantSlug_/$propertyId'
      path: '/widget/$tenantSlug/$propertyId'
      fullPath: '/widget/$tenantSlug/$propertyId'
      preLoaderRoute: typeof WidgetTenantSlugPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/guest-portal/$bookingId': {
      id: '/booking/guest-portal/$bookingId'
      path: '/booking/guest-portal/$bookingId'
      fullPath: '/booking/guest-portal/$bookingId'
      preLoaderRoute: typeof BookingGuestPortalBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/o/$orgSlug': {
      id: '/_app/o/$orgSlug'
      path: '/o/$orgSlug'
      fullPath: '/o/$orgSlug'
      preLoaderRoute: typeof AppOOrgSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/demo/ota/yandex/': {
      id: '/demo/ota/yandex/'
      path: '/ota/yandex'
      fullPath: '/demo/ota/yandex/'
      preLoaderRoute: typeof DemoOtaYandexIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/ota/ostrovok/': {
      id: '/demo/ota/ostrovok/'
      path: '/ota/ostrovok'
      fullPath: '/demo/ota/ostrovok/'
      preLoaderRoute: typeof DemoOtaOstrovokIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/_app/o/$orgSlug/': {
      id: '/_app/o/$orgSlug/'
      path: '/'
      fullPath: '/o/$orgSlug/'
      preLoaderRoute: typeof AppOOrgSlugIndexRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/widget/$tenantSlug_/$propertyId_/guest-and-pay': {
      id: '/widget/$tenantSlug_/$propertyId_/guest-and-pay'
      path: '/widget/$tenantSlug/$propertyId/guest-and-pay'
      fullPath: '/widget/$tenantSlug/$propertyId/guest-and-pay'
      preLoaderRoute: typeof WidgetTenantSlugPropertyIdGuestAndPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/$tenantSlug_/$propertyId_/extras': {
      id: '/widget/$tenantSlug_/$propertyId_/extras'
      path: '/widget/$tenantSlug/$propertyId/extras'
      fullPath: '/widget/$tenantSlug/$propertyId/extras'
      preLoaderRoute: typeof WidgetTenantSlugPropertyIdExtrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/o/$orgSlug/setup': {
      id: '/_app/o/$orgSlug/setup'
      path: '/setup'
      fullPath: '/o/$orgSlug/setup'
      preLoaderRoute: typeof AppOOrgSlugSetupRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/_app/o/$orgSlug/reviews': {
      id: '/_app/o/$orgSlug/reviews'
      path: '/reviews'
      fullPath: '/o/$orgSlug/reviews'
      preLoaderRoute: typeof AppOOrgSlugReviewsRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/_app/o/$orgSlug/receivables': {
      id: '/_app/o/$orgSlug/receivables'
      path: '/receivables'
      fullPath: '/o/$orgSlug/receivables'
      preLoaderRoute: typeof AppOOrgSlugReceivablesRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/_app/o/$orgSlug/grid': {
      id: '/_app/o/$orgSlug/grid'
      path: '/grid'
      fullPath: '/o/$orgSlug/grid'
      preLoaderRoute: typeof AppOOrgSlugGridRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/_app/o/$orgSlug/demo': {
      id: '/_app/o/$orgSlug/demo'
      path: '/demo'
      fullPath: '/o/$orgSlug/demo'
      preLoaderRoute: typeof AppOOrgSlugDemoRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/demo/ota/yandex/success/$orderId': {
      id: '/demo/ota/yandex/success/$orderId'
      path: '/ota/yandex/success/$orderId'
      fullPath: '/demo/ota/yandex/success/$orderId'
      preLoaderRoute: typeof DemoOtaYandexSuccessOrderIdRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/ota/yandex/property/$id': {
      id: '/demo/ota/yandex/property/$id'
      path: '/ota/yandex/property/$id'
      fullPath: '/demo/ota/yandex/property/$id'
      preLoaderRoute: typeof DemoOtaYandexPropertyIdRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/ota/yandex/booking/$bookingToken': {
      id: '/demo/ota/yandex/booking/$bookingToken'
      path: '/ota/yandex/booking/$bookingToken'
      fullPath: '/demo/ota/yandex/booking/$bookingToken'
      preLoaderRoute: typeof DemoOtaYandexBookingBookingTokenRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/ota/ostrovok/success/$orderId': {
      id: '/demo/ota/ostrovok/success/$orderId'
      path: '/ota/ostrovok/success/$orderId'
      fullPath: '/demo/ota/ostrovok/success/$orderId'
      preLoaderRoute: typeof DemoOtaOstrovokSuccessOrderIdRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/ota/ostrovok/property/$id': {
      id: '/demo/ota/ostrovok/property/$id'
      path: '/ota/ostrovok/property/$id'
      fullPath: '/demo/ota/ostrovok/property/$id'
      preLoaderRoute: typeof DemoOtaOstrovokPropertyIdRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/ota/ostrovok/booking/$partnerOrderId': {
      id: '/demo/ota/ostrovok/booking/$partnerOrderId'
      path: '/ota/ostrovok/booking/$partnerOrderId'
      fullPath: '/demo/ota/ostrovok/booking/$partnerOrderId'
      preLoaderRoute: typeof DemoOtaOstrovokBookingPartnerOrderIdRouteImport
      parentRoute: typeof DemoRoute
    }
    '/_app/o/$orgSlug/admin/tax': {
      id: '/_app/o/$orgSlug/admin/tax'
      path: '/admin/tax'
      fullPath: '/o/$orgSlug/admin/tax'
      preLoaderRoute: typeof AppOOrgSlugAdminTaxRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/_app/o/$orgSlug/admin/notifications': {
      id: '/_app/o/$orgSlug/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/o/$orgSlug/admin/notifications'
      preLoaderRoute: typeof AppOOrgSlugAdminNotificationsRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/_app/o/$orgSlug/admin/migration-registrations': {
      id: '/_app/o/$orgSlug/admin/migration-registrations'
      path: '/admin/migration-registrations'
      fullPath: '/o/$orgSlug/admin/migration-registrations'
      preLoaderRoute: typeof AppOOrgSlugAdminMigrationRegistrationsRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/_app/o/$orgSlug/admin/channels': {
      id: '/_app/o/$orgSlug/admin/channels'
      path: '/admin/channels'
      fullPath: '/o/$orgSlug/admin/channels'
      preLoaderRoute: typeof AppOOrgSlugAdminChannelsRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/_app/o/$orgSlug/account/security': {
      id: '/_app/o/$orgSlug/account/security'
      path: '/account/security'
      fullPath: '/o/$orgSlug/account/security'
      preLoaderRoute: typeof AppOOrgSlugAccountSecurityRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/_app/o/$orgSlug/properties/$propertyId/inventory': {
      id: '/_app/o/$orgSlug/properties/$propertyId/inventory'
      path: '/properties/$propertyId/inventory'
      fullPath: '/o/$orgSlug/properties/$propertyId/inventory'
      preLoaderRoute: typeof AppOOrgSlugPropertiesPropertyIdInventoryRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/_app/o/$orgSlug/properties/$propertyId/content': {
      id: '/_app/o/$orgSlug/properties/$propertyId/content'
      path: '/properties/$propertyId/content'
      fullPath: '/o/$orgSlug/properties/$propertyId/content'
      preLoaderRoute: typeof AppOOrgSlugPropertiesPropertyIdContentRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/_app/o/$orgSlug/properties/$propertyId/inventory/rooms': {
      id: '/_app/o/$orgSlug/properties/$propertyId/inventory/rooms'
      path: '/rooms'
      fullPath: '/o/$orgSlug/properties/$propertyId/inventory/rooms'
      preLoaderRoute: typeof AppOOrgSlugPropertiesPropertyIdInventoryRoomsRouteImport
      parentRoute: typeof AppOOrgSlugPropertiesPropertyIdInventoryRoute
    }
    '/_app/o/$orgSlug/properties/$propertyId/inventory/rate-plans': {
      id: '/_app/o/$orgSlug/properties/$propertyId/inventory/rate-plans'
      path: '/rate-plans'
      fullPath: '/o/$orgSlug/properties/$propertyId/inventory/rate-plans'
      preLoaderRoute: typeof AppOOrgSlugPropertiesPropertyIdInventoryRatePlansRouteImport
      parentRoute: typeof AppOOrgSlugPropertiesPropertyIdInventoryRoute
    }
    '/_app/o/$orgSlug/properties/$propertyId/inventory/prices': {
      id: '/_app/o/$orgSlug/properties/$propertyId/inventory/prices'
      path: '/prices'
      fullPath: '/o/$orgSlug/properties/$propertyId/inventory/prices'
      preLoaderRoute: typeof AppOOrgSlugPropertiesPropertyIdInventoryPricesRouteImport
      parentRoute: typeof AppOOrgSlugPropertiesPropertyIdInventoryRoute
    }
    '/_app/o/$orgSlug/bookings/$bookingId/folios/$folioId': {
      id: '/_app/o/$orgSlug/bookings/$bookingId/folios/$folioId'
      path: '/bookings/$bookingId/folios/$folioId'
      fullPath: '/o/$orgSlug/bookings/$bookingId/folios/$folioId'
      preLoaderRoute: typeof AppOOrgSlugBookingsBookingIdFoliosFolioIdRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
  }
}

interface AppOOrgSlugPropertiesPropertyIdInventoryRouteChildren {
  AppOOrgSlugPropertiesPropertyIdInventoryPricesRoute: typeof AppOOrgSlugPropertiesPropertyIdInventoryPricesRoute
  AppOOrgSlugPropertiesPropertyIdInventoryRatePlansRoute: typeof AppOOrgSlugPropertiesPropertyIdInventoryRatePlansRoute
  AppOOrgSlugPropertiesPropertyIdInventoryRoomsRoute: typeof AppOOrgSlugPropertiesPropertyIdInventoryRoomsRoute
}

const AppOOrgSlugPropertiesPropertyIdInventoryRouteChildren: AppOOrgSlugPropertiesPropertyIdInventoryRouteChildren =
  {
    AppOOrgSlugPropertiesPropertyIdInventoryPricesRoute:
      AppOOrgSlugPropertiesPropertyIdInventoryPricesRoute,
    AppOOrgSlugPropertiesPropertyIdInventoryRatePlansRoute:
      AppOOrgSlugPropertiesPropertyIdInventoryRatePlansRoute,
    AppOOrgSlugPropertiesPropertyIdInventoryRoomsRoute:
      AppOOrgSlugPropertiesPropertyIdInventoryRoomsRoute,
  }

const AppOOrgSlugPropertiesPropertyIdInventoryRouteWithChildren =
  AppOOrgSlugPropertiesPropertyIdInventoryRoute._addFileChildren(
    AppOOrgSlugPropertiesPropertyIdInventoryRouteChildren,
  )

interface AppOOrgSlugRouteChildren {
  AppOOrgSlugDemoRoute: typeof AppOOrgSlugDemoRoute
  AppOOrgSlugGridRoute: typeof AppOOrgSlugGridRoute
  AppOOrgSlugReceivablesRoute: typeof AppOOrgSlugReceivablesRoute
  AppOOrgSlugReviewsRoute: typeof AppOOrgSlugReviewsRoute
  AppOOrgSlugSetupRoute: typeof AppOOrgSlugSetupRoute
  AppOOrgSlugIndexRoute: typeof AppOOrgSlugIndexRoute
  AppOOrgSlugAccountSecurityRoute: typeof AppOOrgSlugAccountSecurityRoute
  AppOOrgSlugAdminChannelsRoute: typeof AppOOrgSlugAdminChannelsRoute
  AppOOrgSlugAdminMigrationRegistrationsRoute: typeof AppOOrgSlugAdminMigrationRegistrationsRoute
  AppOOrgSlugAdminNotificationsRoute: typeof AppOOrgSlugAdminNotificationsRoute
  AppOOrgSlugAdminTaxRoute: typeof AppOOrgSlugAdminTaxRoute
  AppOOrgSlugPropertiesPropertyIdContentRoute: typeof AppOOrgSlugPropertiesPropertyIdContentRoute
  AppOOrgSlugPropertiesPropertyIdInventoryRoute: typeof AppOOrgSlugPropertiesPropertyIdInventoryRouteWithChildren
  AppOOrgSlugBookingsBookingIdFoliosFolioIdRoute: typeof AppOOrgSlugBookingsBookingIdFoliosFolioIdRoute
}

const AppOOrgSlugRouteChildren: AppOOrgSlugRouteChildren = {
  AppOOrgSlugDemoRoute: AppOOrgSlugDemoRoute,
  AppOOrgSlugGridRoute: AppOOrgSlugGridRoute,
  AppOOrgSlugReceivablesRoute: AppOOrgSlugReceivablesRoute,
  AppOOrgSlugReviewsRoute: AppOOrgSlugReviewsRoute,
  AppOOrgSlugSetupRoute: AppOOrgSlugSetupRoute,
  AppOOrgSlugIndexRoute: AppOOrgSlugIndexRoute,
  AppOOrgSlugAccountSecurityRoute: AppOOrgSlugAccountSecurityRoute,
  AppOOrgSlugAdminChannelsRoute: AppOOrgSlugAdminChannelsRoute,
  AppOOrgSlugAdminMigrationRegistrationsRoute:
    AppOOrgSlugAdminMigrationRegistrationsRoute,
  AppOOrgSlugAdminNotificationsRoute: AppOOrgSlugAdminNotificationsRoute,
  AppOOrgSlugAdminTaxRoute: AppOOrgSlugAdminTaxRoute,
  AppOOrgSlugPropertiesPropertyIdContentRoute:
    AppOOrgSlugPropertiesPropertyIdContentRoute,
  AppOOrgSlugPropertiesPropertyIdInventoryRoute:
    AppOOrgSlugPropertiesPropertyIdInventoryRouteWithChildren,
  AppOOrgSlugBookingsBookingIdFoliosFolioIdRoute:
    AppOOrgSlugBookingsBookingIdFoliosFolioIdRoute,
}

const AppOOrgSlugRouteWithChildren = AppOOrgSlugRoute._addFileChildren(
  AppOOrgSlugRouteChildren,
)

interface AppRouteChildren {
  AppOSelectRoute: typeof AppOSelectRoute
  AppOOrgSlugRoute: typeof AppOOrgSlugRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppOSelectRoute: AppOSelectRoute,
  AppOOrgSlugRoute: AppOOrgSlugRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DemoRouteChildren {
  DemoShowcaseRoute: typeof DemoShowcaseRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DemoOtaOstrovokIndexRoute: typeof DemoOtaOstrovokIndexRoute
  DemoOtaYandexIndexRoute: typeof DemoOtaYandexIndexRoute
  DemoOtaOstrovokBookingPartnerOrderIdRoute: typeof DemoOtaOstrovokBookingPartnerOrderIdRoute
  DemoOtaOstrovokPropertyIdRoute: typeof DemoOtaOstrovokPropertyIdRoute
  DemoOtaOstrovokSuccessOrderIdRoute: typeof DemoOtaOstrovokSuccessOrderIdRoute
  DemoOtaYandexBookingBookingTokenRoute: typeof DemoOtaYandexBookingBookingTokenRoute
  DemoOtaYandexPropertyIdRoute: typeof DemoOtaYandexPropertyIdRoute
  DemoOtaYandexSuccessOrderIdRoute: typeof DemoOtaYandexSuccessOrderIdRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoShowcaseRoute: DemoShowcaseRoute,
  DemoIndexRoute: DemoIndexRoute,
  DemoOtaOstrovokIndexRoute: DemoOtaOstrovokIndexRoute,
  DemoOtaYandexIndexRoute: DemoOtaYandexIndexRoute,
  DemoOtaOstrovokBookingPartnerOrderIdRoute:
    DemoOtaOstrovokBookingPartnerOrderIdRoute,
  DemoOtaOstrovokPropertyIdRoute: DemoOtaOstrovokPropertyIdRoute,
  DemoOtaOstrovokSuccessOrderIdRoute: DemoOtaOstrovokSuccessOrderIdRoute,
  DemoOtaYandexBookingBookingTokenRoute: DemoOtaYandexBookingBookingTokenRoute,
  DemoOtaYandexPropertyIdRoute: DemoOtaYandexPropertyIdRoute,
  DemoOtaYandexSuccessOrderIdRoute: DemoOtaYandexSuccessOrderIdRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  WelcomeRoute: WelcomeRoute,
  BookingJwtRoute: BookingJwtRoute,
  WidgetTenantSlugRoute: WidgetTenantSlugRoute,
  BookingGuestPortalBookingIdRoute: BookingGuestPortalBookingIdRoute,
  WidgetTenantSlugPropertyIdRoute: WidgetTenantSlugPropertyIdRoute,
  WidgetTenantSlugPropertyIdExtrasRoute: WidgetTenantSlugPropertyIdExtrasRoute,
  WidgetTenantSlugPropertyIdGuestAndPayRoute:
    WidgetTenantSlugPropertyIdGuestAndPayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
