/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as WidgetTenantSlugRouteImport } from './routes/widget.$tenantSlug'
import { Route as AppOSelectRouteImport } from './routes/_app.o-select'
import { Route as WidgetTenantSlugPropertyIdRouteImport } from './routes/widget.$tenantSlug_.$propertyId'
import { Route as AppOOrgSlugRouteImport } from './routes/_app.o.$orgSlug'
import { Route as AppOOrgSlugIndexRouteImport } from './routes/_app.o.$orgSlug.index'
import { Route as WidgetTenantSlugPropertyIdGuestAndPayRouteImport } from './routes/widget.$tenantSlug_.$propertyId_.guest-and-pay'
import { Route as WidgetTenantSlugPropertyIdExtrasRouteImport } from './routes/widget.$tenantSlug_.$propertyId_.extras'
import { Route as AppOOrgSlugSetupRouteImport } from './routes/_app.o.$orgSlug.setup'
import { Route as AppOOrgSlugReceivablesRouteImport } from './routes/_app.o.$orgSlug.receivables'
import { Route as AppOOrgSlugGridRouteImport } from './routes/_app.o.$orgSlug.grid'
import { Route as AppOOrgSlugAdminTaxRouteImport } from './routes/_app.o.$orgSlug.admin.tax'
import { Route as AppOOrgSlugAdminNotificationsRouteImport } from './routes/_app.o.$orgSlug.admin.notifications'
import { Route as AppOOrgSlugAdminMigrationRegistrationsRouteImport } from './routes/_app.o.$orgSlug.admin.migration-registrations'
import { Route as AppOOrgSlugAccountSecurityRouteImport } from './routes/_app.o.$orgSlug.account.security'
import { Route as AppOOrgSlugPropertiesPropertyIdContentRouteImport } from './routes/_app.o.$orgSlug.properties.$propertyId.content'
import { Route as AppOOrgSlugBookingsBookingIdFoliosFolioIdRouteImport } from './routes/_app.o.$orgSlug.bookings.$bookingId.folios.$folioId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const WidgetTenantSlugRoute = WidgetTenantSlugRouteImport.update({
  id: '/widget/$tenantSlug',
  path: '/widget/$tenantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOSelectRoute = AppOSelectRouteImport.update({
  id: '/o-select',
  path: '/o-select',
  getParentRoute: () => AppRoute,
} as any)
const WidgetTenantSlugPropertyIdRoute =
  WidgetTenantSlugPropertyIdRouteImport.update({
    id: '/widget/$tenantSlug_/$propertyId',
    path: '/widget/$tenantSlug/$propertyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOOrgSlugRoute = AppOOrgSlugRouteImport.update({
  id: '/o/$orgSlug',
  path: '/o/$orgSlug',
  getParentRoute: () => AppRoute,
} as any)
const AppOOrgSlugIndexRoute = AppOOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOOrgSlugRoute,
} as any)
const WidgetTenantSlugPropertyIdGuestAndPayRoute =
  WidgetTenantSlugPropertyIdGuestAndPayRouteImport.update({
    id: '/widget/$tenantSlug_/$propertyId_/guest-and-pay',
    path: '/widget/$tenantSlug/$propertyId/guest-and-pay',
    getParentRoute: () => rootRouteImport,
  } as any)
const WidgetTenantSlugPropertyIdExtrasRoute =
  WidgetTenantSlugPropertyIdExtrasRouteImport.update({
    id: '/widget/$tenantSlug_/$propertyId_/extras',
    path: '/widget/$tenantSlug/$propertyId/extras',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOOrgSlugSetupRoute = AppOOrgSlugSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppOOrgSlugRoute,
} as any)
const AppOOrgSlugReceivablesRoute = AppOOrgSlugReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => AppOOrgSlugRoute,
} as any)
const AppOOrgSlugGridRoute = AppOOrgSlugGridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => AppOOrgSlugRoute,
} as any)
const AppOOrgSlugAdminTaxRoute = AppOOrgSlugAdminTaxRouteImport.update({
  id: '/admin/tax',
  path: '/admin/tax',
  getParentRoute: () => AppOOrgSlugRoute,
} as any)
const AppOOrgSlugAdminNotificationsRoute =
  AppOOrgSlugAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AppOOrgSlugRoute,
  } as any)
const AppOOrgSlugAdminMigrationRegistrationsRoute =
  AppOOrgSlugAdminMigrationRegistrationsRouteImport.update({
    id: '/admin/migration-registrations',
    path: '/admin/migration-registrations',
    getParentRoute: () => AppOOrgSlugRoute,
  } as any)
const AppOOrgSlugAccountSecurityRoute =
  AppOOrgSlugAccountSecurityRouteImport.update({
    id: '/account/security',
    path: '/account/security',
    getParentRoute: () => AppOOrgSlugRoute,
  } as any)
const AppOOrgSlugPropertiesPropertyIdContentRoute =
  AppOOrgSlugPropertiesPropertyIdContentRouteImport.update({
    id: '/properties/$propertyId/content',
    path: '/properties/$propertyId/content',
    getParentRoute: () => AppOOrgSlugRoute,
  } as any)
const AppOOrgSlugBookingsBookingIdFoliosFolioIdRoute =
  AppOOrgSlugBookingsBookingIdFoliosFolioIdRouteImport.update({
    id: '/bookings/$bookingId/folios/$folioId',
    path: '/bookings/$bookingId/folios/$folioId',
    getParentRoute: () => AppOOrgSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/o-select': typeof AppOSelectRoute
  '/widget/$tenantSlug': typeof WidgetTenantSlugRoute
  '/o/$orgSlug': typeof AppOOrgSlugRouteWithChildren
  '/widget/$tenantSlug/$propertyId': typeof WidgetTenantSlugPropertyIdRoute
  '/o/$orgSlug/grid': typeof AppOOrgSlugGridRoute
  '/o/$orgSlug/receivables': typeof AppOOrgSlugReceivablesRoute
  '/o/$orgSlug/setup': typeof AppOOrgSlugSetupRoute
  '/widget/$tenantSlug/$propertyId/extras': typeof WidgetTenantSlugPropertyIdExtrasRoute
  '/widget/$tenantSlug/$propertyId/guest-and-pay': typeof WidgetTenantSlugPropertyIdGuestAndPayRoute
  '/o/$orgSlug/': typeof AppOOrgSlugIndexRoute
  '/o/$orgSlug/account/security': typeof AppOOrgSlugAccountSecurityRoute
  '/o/$orgSlug/admin/migration-registrations': typeof AppOOrgSlugAdminMigrationRegistrationsRoute
  '/o/$orgSlug/admin/notifications': typeof AppOOrgSlugAdminNotificationsRoute
  '/o/$orgSlug/admin/tax': typeof AppOOrgSlugAdminTaxRoute
  '/o/$orgSlug/properties/$propertyId/content': typeof AppOOrgSlugPropertiesPropertyIdContentRoute
  '/o/$orgSlug/bookings/$bookingId/folios/$folioId': typeof AppOOrgSlugBookingsBookingIdFoliosFolioIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/o-select': typeof AppOSelectRoute
  '/widget/$tenantSlug': typeof WidgetTenantSlugRoute
  '/': typeof AppIndexRoute
  '/widget/$tenantSlug/$propertyId': typeof WidgetTenantSlugPropertyIdRoute
  '/o/$orgSlug/grid': typeof AppOOrgSlugGridRoute
  '/o/$orgSlug/receivables': typeof AppOOrgSlugReceivablesRoute
  '/o/$orgSlug/setup': typeof AppOOrgSlugSetupRoute
  '/widget/$tenantSlug/$propertyId/extras': typeof WidgetTenantSlugPropertyIdExtrasRoute
  '/widget/$tenantSlug/$propertyId/guest-and-pay': typeof WidgetTenantSlugPropertyIdGuestAndPayRoute
  '/o/$orgSlug': typeof AppOOrgSlugIndexRoute
  '/o/$orgSlug/account/security': typeof AppOOrgSlugAccountSecurityRoute
  '/o/$orgSlug/admin/migration-registrations': typeof AppOOrgSlugAdminMigrationRegistrationsRoute
  '/o/$orgSlug/admin/notifications': typeof AppOOrgSlugAdminNotificationsRoute
  '/o/$orgSlug/admin/tax': typeof AppOOrgSlugAdminTaxRoute
  '/o/$orgSlug/properties/$propertyId/content': typeof AppOOrgSlugPropertiesPropertyIdContentRoute
  '/o/$orgSlug/bookings/$bookingId/folios/$folioId': typeof AppOOrgSlugBookingsBookingIdFoliosFolioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/_app/o-select': typeof AppOSelectRoute
  '/widget/$tenantSlug': typeof WidgetTenantSlugRoute
  '/_app/': typeof AppIndexRoute
  '/_app/o/$orgSlug': typeof AppOOrgSlugRouteWithChildren
  '/widget/$tenantSlug_/$propertyId': typeof WidgetTenantSlugPropertyIdRoute
  '/_app/o/$orgSlug/grid': typeof AppOOrgSlugGridRoute
  '/_app/o/$orgSlug/receivables': typeof AppOOrgSlugReceivablesRoute
  '/_app/o/$orgSlug/setup': typeof AppOOrgSlugSetupRoute
  '/widget/$tenantSlug_/$propertyId_/extras': typeof WidgetTenantSlugPropertyIdExtrasRoute
  '/widget/$tenantSlug_/$propertyId_/guest-and-pay': typeof WidgetTenantSlugPropertyIdGuestAndPayRoute
  '/_app/o/$orgSlug/': typeof AppOOrgSlugIndexRoute
  '/_app/o/$orgSlug/account/security': typeof AppOOrgSlugAccountSecurityRoute
  '/_app/o/$orgSlug/admin/migration-registrations': typeof AppOOrgSlugAdminMigrationRegistrationsRoute
  '/_app/o/$orgSlug/admin/notifications': typeof AppOOrgSlugAdminNotificationsRoute
  '/_app/o/$orgSlug/admin/tax': typeof AppOOrgSlugAdminTaxRoute
  '/_app/o/$orgSlug/properties/$propertyId/content': typeof AppOOrgSlugPropertiesPropertyIdContentRoute
  '/_app/o/$orgSlug/bookings/$bookingId/folios/$folioId': typeof AppOOrgSlugBookingsBookingIdFoliosFolioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/o-select'
    | '/widget/$tenantSlug'
    | '/o/$orgSlug'
    | '/widget/$tenantSlug/$propertyId'
    | '/o/$orgSlug/grid'
    | '/o/$orgSlug/receivables'
    | '/o/$orgSlug/setup'
    | '/widget/$tenantSlug/$propertyId/extras'
    | '/widget/$tenantSlug/$propertyId/guest-and-pay'
    | '/o/$orgSlug/'
    | '/o/$orgSlug/account/security'
    | '/o/$orgSlug/admin/migration-registrations'
    | '/o/$orgSlug/admin/notifications'
    | '/o/$orgSlug/admin/tax'
    | '/o/$orgSlug/properties/$propertyId/content'
    | '/o/$orgSlug/bookings/$bookingId/folios/$folioId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/privacy'
    | '/signup'
    | '/o-select'
    | '/widget/$tenantSlug'
    | '/'
    | '/widget/$tenantSlug/$propertyId'
    | '/o/$orgSlug/grid'
    | '/o/$orgSlug/receivables'
    | '/o/$orgSlug/setup'
    | '/widget/$tenantSlug/$propertyId/extras'
    | '/widget/$tenantSlug/$propertyId/guest-and-pay'
    | '/o/$orgSlug'
    | '/o/$orgSlug/account/security'
    | '/o/$orgSlug/admin/migration-registrations'
    | '/o/$orgSlug/admin/notifications'
    | '/o/$orgSlug/admin/tax'
    | '/o/$orgSlug/properties/$propertyId/content'
    | '/o/$orgSlug/bookings/$bookingId/folios/$folioId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/_app/o-select'
    | '/widget/$tenantSlug'
    | '/_app/'
    | '/_app/o/$orgSlug'
    | '/widget/$tenantSlug_/$propertyId'
    | '/_app/o/$orgSlug/grid'
    | '/_app/o/$orgSlug/receivables'
    | '/_app/o/$orgSlug/setup'
    | '/widget/$tenantSlug_/$propertyId_/extras'
    | '/widget/$tenantSlug_/$propertyId_/guest-and-pay'
    | '/_app/o/$orgSlug/'
    | '/_app/o/$orgSlug/account/security'
    | '/_app/o/$orgSlug/admin/migration-registrations'
    | '/_app/o/$orgSlug/admin/notifications'
    | '/_app/o/$orgSlug/admin/tax'
    | '/_app/o/$orgSlug/properties/$propertyId/content'
    | '/_app/o/$orgSlug/bookings/$bookingId/folios/$folioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  WidgetTenantSlugRoute: typeof WidgetTenantSlugRoute
  WidgetTenantSlugPropertyIdRoute: typeof WidgetTenantSlugPropertyIdRoute
  WidgetTenantSlugPropertyIdExtrasRoute: typeof WidgetTenantSlugPropertyIdExtrasRoute
  WidgetTenantSlugPropertyIdGuestAndPayRoute: typeof WidgetTenantSlugPropertyIdGuestAndPayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/widget/$tenantSlug': {
      id: '/widget/$tenantSlug'
      path: '/widget/$tenantSlug'
      fullPath: '/widget/$tenantSlug'
      preLoaderRoute: typeof WidgetTenantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/o-select': {
      id: '/_app/o-select'
      path: '/o-select'
      fullPath: '/o-select'
      preLoaderRoute: typeof AppOSelectRouteImport
      parentRoute: typeof AppRoute
    }
    '/widget/$tenantSlug_/$propertyId': {
      id: '/widget/$tenantSlug_/$propertyId'
      path: '/widget/$tenantSlug/$propertyId'
      fullPath: '/widget/$tenantSlug/$propertyId'
      preLoaderRoute: typeof WidgetTenantSlugPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/o/$orgSlug': {
      id: '/_app/o/$orgSlug'
      path: '/o/$orgSlug'
      fullPath: '/o/$orgSlug'
      preLoaderRoute: typeof AppOOrgSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/o/$orgSlug/': {
      id: '/_app/o/$orgSlug/'
      path: '/'
      fullPath: '/o/$orgSlug/'
      preLoaderRoute: typeof AppOOrgSlugIndexRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/widget/$tenantSlug_/$propertyId_/guest-and-pay': {
      id: '/widget/$tenantSlug_/$propertyId_/guest-and-pay'
      path: '/widget/$tenantSlug/$propertyId/guest-and-pay'
      fullPath: '/widget/$tenantSlug/$propertyId/guest-and-pay'
      preLoaderRoute: typeof WidgetTenantSlugPropertyIdGuestAndPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/$tenantSlug_/$propertyId_/extras': {
      id: '/widget/$tenantSlug_/$propertyId_/extras'
      path: '/widget/$tenantSlug/$propertyId/extras'
      fullPath: '/widget/$tenantSlug/$propertyId/extras'
      preLoaderRoute: typeof WidgetTenantSlugPropertyIdExtrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/o/$orgSlug/setup': {
      id: '/_app/o/$orgSlug/setup'
      path: '/setup'
      fullPath: '/o/$orgSlug/setup'
      preLoaderRoute: typeof AppOOrgSlugSetupRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/_app/o/$orgSlug/receivables': {
      id: '/_app/o/$orgSlug/receivables'
      path: '/receivables'
      fullPath: '/o/$orgSlug/receivables'
      preLoaderRoute: typeof AppOOrgSlugReceivablesRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/_app/o/$orgSlug/grid': {
      id: '/_app/o/$orgSlug/grid'
      path: '/grid'
      fullPath: '/o/$orgSlug/grid'
      preLoaderRoute: typeof AppOOrgSlugGridRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/_app/o/$orgSlug/admin/tax': {
      id: '/_app/o/$orgSlug/admin/tax'
      path: '/admin/tax'
      fullPath: '/o/$orgSlug/admin/tax'
      preLoaderRoute: typeof AppOOrgSlugAdminTaxRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/_app/o/$orgSlug/admin/notifications': {
      id: '/_app/o/$orgSlug/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/o/$orgSlug/admin/notifications'
      preLoaderRoute: typeof AppOOrgSlugAdminNotificationsRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/_app/o/$orgSlug/admin/migration-registrations': {
      id: '/_app/o/$orgSlug/admin/migration-registrations'
      path: '/admin/migration-registrations'
      fullPath: '/o/$orgSlug/admin/migration-registrations'
      preLoaderRoute: typeof AppOOrgSlugAdminMigrationRegistrationsRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/_app/o/$orgSlug/account/security': {
      id: '/_app/o/$orgSlug/account/security'
      path: '/account/security'
      fullPath: '/o/$orgSlug/account/security'
      preLoaderRoute: typeof AppOOrgSlugAccountSecurityRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/_app/o/$orgSlug/properties/$propertyId/content': {
      id: '/_app/o/$orgSlug/properties/$propertyId/content'
      path: '/properties/$propertyId/content'
      fullPath: '/o/$orgSlug/properties/$propertyId/content'
      preLoaderRoute: typeof AppOOrgSlugPropertiesPropertyIdContentRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
    '/_app/o/$orgSlug/bookings/$bookingId/folios/$folioId': {
      id: '/_app/o/$orgSlug/bookings/$bookingId/folios/$folioId'
      path: '/bookings/$bookingId/folios/$folioId'
      fullPath: '/o/$orgSlug/bookings/$bookingId/folios/$folioId'
      preLoaderRoute: typeof AppOOrgSlugBookingsBookingIdFoliosFolioIdRouteImport
      parentRoute: typeof AppOOrgSlugRoute
    }
  }
}

interface AppOOrgSlugRouteChildren {
  AppOOrgSlugGridRoute: typeof AppOOrgSlugGridRoute
  AppOOrgSlugReceivablesRoute: typeof AppOOrgSlugReceivablesRoute
  AppOOrgSlugSetupRoute: typeof AppOOrgSlugSetupRoute
  AppOOrgSlugIndexRoute: typeof AppOOrgSlugIndexRoute
  AppOOrgSlugAccountSecurityRoute: typeof AppOOrgSlugAccountSecurityRoute
  AppOOrgSlugAdminMigrationRegistrationsRoute: typeof AppOOrgSlugAdminMigrationRegistrationsRoute
  AppOOrgSlugAdminNotificationsRoute: typeof AppOOrgSlugAdminNotificationsRoute
  AppOOrgSlugAdminTaxRoute: typeof AppOOrgSlugAdminTaxRoute
  AppOOrgSlugPropertiesPropertyIdContentRoute: typeof AppOOrgSlugPropertiesPropertyIdContentRoute
  AppOOrgSlugBookingsBookingIdFoliosFolioIdRoute: typeof AppOOrgSlugBookingsBookingIdFoliosFolioIdRoute
}

const AppOOrgSlugRouteChildren: AppOOrgSlugRouteChildren = {
  AppOOrgSlugGridRoute: AppOOrgSlugGridRoute,
  AppOOrgSlugReceivablesRoute: AppOOrgSlugReceivablesRoute,
  AppOOrgSlugSetupRoute: AppOOrgSlugSetupRoute,
  AppOOrgSlugIndexRoute: AppOOrgSlugIndexRoute,
  AppOOrgSlugAccountSecurityRoute: AppOOrgSlugAccountSecurityRoute,
  AppOOrgSlugAdminMigrationRegistrationsRoute:
    AppOOrgSlugAdminMigrationRegistrationsRoute,
  AppOOrgSlugAdminNotificationsRoute: AppOOrgSlugAdminNotificationsRoute,
  AppOOrgSlugAdminTaxRoute: AppOOrgSlugAdminTaxRoute,
  AppOOrgSlugPropertiesPropertyIdContentRoute:
    AppOOrgSlugPropertiesPropertyIdContentRoute,
  AppOOrgSlugBookingsBookingIdFoliosFolioIdRoute:
    AppOOrgSlugBookingsBookingIdFoliosFolioIdRoute,
}

const AppOOrgSlugRouteWithChildren = AppOOrgSlugRoute._addFileChildren(
  AppOOrgSlugRouteChildren,
)

interface AppRouteChildren {
  AppOSelectRoute: typeof AppOSelectRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOOrgSlugRoute: typeof AppOOrgSlugRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppOSelectRoute: AppOSelectRoute,
  AppIndexRoute: AppIndexRoute,
  AppOOrgSlugRoute: AppOOrgSlugRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  WidgetTenantSlugRoute: WidgetTenantSlugRoute,
  WidgetTenantSlugPropertyIdRoute: WidgetTenantSlugPropertyIdRoute,
  WidgetTenantSlugPropertyIdExtrasRoute: WidgetTenantSlugPropertyIdExtrasRoute,
  WidgetTenantSlugPropertyIdGuestAndPayRoute:
    WidgetTenantSlugPropertyIdGuestAndPayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
